name = "email-to-discord-embed-queue"
main = "src/index.ts"
compatibility_date = "2023-02-20"
usage_model = "unbound"
workers_dev = false

[[r2_buckets]]
binding = "R2EMAILS" # <~ valid JavaScript variable name
bucket_name = "eemailme"

# Worker also receives messages from the Queue, named "my-queue".
[[queues.consumers]]
  queue = "email-to-discord-embed-queue"
  max_batch_size = 100   # Max messages per batch
  max_batch_timeout = 30 # Max seconds to wait before batch is full
  max_retries = 0       # Max retries per batch